package demo;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.input.InputMethodEvent;

import javafx.scene.control.DatePicker;

public class StockViewController {
	@FXML
	private DatePicker stockDayPicker;
	@FXML
	private DatePicker changeStockPicker;
	@FXML
	private DatePicker stockRangePicker;
	@FXML
	private ListView stockRangeList;
	@FXML
	private Text closeText;
	@FXML
	private Text openText;
	@FXML
	private Text highText;
	@FXML
	private Text lowText;
	@FXML
	private Text volumeText;
	@FXML
	private Text highestText;
	@FXML
	private Text avgText;
	@FXML
	private Text lowestText;
	@FXML
	private Text dateHighestText;
	@FXML
	private Text dateLowestText;
	@FXML
	private DatePicker stockDayPicker1;
	@FXML
	private DatePicker changeStockPicker1;
	@FXML
	private DatePicker stockRangePicker1;
	@FXML
	private ListView stockRangeList1;
	@FXML
	private Text closeText1;
	@FXML
	private Text openText1;
	@FXML
	private Text highText1;
	@FXML
	private Text lowText1;
	@FXML
	private Text volumeText1;
	@FXML
	private Text highestText1;
	@FXML
	private Text avgText1;
	@FXML
	private Text lowestText1;
	@FXML
	private Text dateHighestText1;
	@FXML
	private Text dateLowestText1;

	// Event Listener on DatePicker[#stockDayPicker].onAction
	@FXML
	public void findStock1(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#changeStockPicker].onInputMethodTextChanged
	@FXML
	public void createNewStock1(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#stockRangePicker].onInputMethodTextChanged
	@FXML
	public void addToList1(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#stockDayPicker1].onInputMethodTextChanged
	@FXML
	public void findStock2(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#changeStockPicker1].onInputMethodTextChanged
	@FXML
	public void createNewStock2(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#stockRangePicker1].onInputMethodTextChanged
	@FXML
	public void addToList2(InputMethodEvent event) {
		// TODO Autogenerated
	}
}
