package demo;

import java.util.Date;

import alerts.ClosedAlert;
import alerts.MetaDataAlert;
import factories.DataFactory;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.control.ListView;
import javafx.scene.text.Text;
import models.StockData;
import models.StockDay;

public class StockViewController {
	//private StockData msft = DataFactory.generateDataURL("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&outputsize=full&apikey=8Y8VNRTWK1PBQ5AU&dataype=json");
	//private StockData adx = DataFactory.generateDataURL("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=ADX&outputsize=full&apikey=8Y8VNRTWK1PBQ5AU&dataype=json");
	private StockData msft = DataFactory.generateDataString("C:\\Users\\rober\\eclipse-workspace-Hackathon\\CSE218-finalproject\\src\\msft.json");
	private StockData adx = DataFactory.generateDataString("C:\\Users\\rober\\eclipse-workspace-Hackathon\\CSE218-finalproject\\src\\adx.json");
	@FXML
	private DatePicker stockDayPicker;
	@FXML
	private DatePicker changeStockPicker;
	@FXML
	private DatePicker stockRangePicker;
	@FXML
	private ListView stockRangeList;
	@FXML
	private Text closeText;
	@FXML
	private Text openText;
	@FXML
	private Text highText;
	@FXML
	private Text lowText;
	@FXML
	private Text volumeText;
	@FXML
	private Text highestText;
	@FXML
	private Text avgText;
	@FXML
	private Text lowestText;
	@FXML
	private Text dateHighestText;
	@FXML
	private Text dateLowestText;
	@FXML
	private DatePicker stockDayPicker1;
	@FXML
	private DatePicker changeStockPicker1;
	@FXML
	private DatePicker stockRangePicker1;
	@FXML
	private ListView stockRangeList1;
	@FXML
	private Text closeText1;
	@FXML
	private Text openText1;
	@FXML
	private Text highText1;
	@FXML
	private Text lowText1;
	@FXML
	private Text volumeText1;
	@FXML
	private Text highestText1;
	@FXML
	private Text avgText1;
	@FXML
	private Text lowestText1;
	@FXML
	private Text dateHighestText1;
	@FXML
	private Text dateLowestText1;
	private ClosedAlert closedAlert = new ClosedAlert();
	private MetaDataAlert msftMeta = new MetaDataAlert(msft);
	private MetaDataAlert adxMeta = new MetaDataAlert(adx);
    @FXML
    private Button metaDataButton;
    @FXML
    private Button metaDataButton1;

	// Event Listener on DatePicker[#stockDayPicker].onAction
	@FXML
	public void findStock1(ActionEvent event) {
		//1986-13-3
		Date openDate = new Date("1986-3-13");
		StockDay day = msft.getStocks().get(stockDayPicker.getValue().toString());
//		if((stockDayPicker.getValue() <  openDate) {
//			System.out.println("NOT EVEN OPEN YET BRO");
//		}
		if(day == null) {
			closedAlert.showAndWait();
		} else {
			openText.setText(String.valueOf(day.getOpen()));
			closeText.setText(String.valueOf(day.getClose()));
			highText.setText(String.valueOf(day.getHigh()));
			lowText.setText(String.valueOf(day.getLow()));
			volumeText.setText(String.valueOf(day.getVolume()));
		}
	}
	@FXML
	public void createNewStock1(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#stockRangePicker].onInputMethodTextChanged
	@FXML
	public void addToList1(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void findStock2(ActionEvent event) {
		StockDay day = adx.getStocks().get(stockDayPicker1.getValue().toString());
		if(day == null) {
			closedAlert.showAndWait();
		} else {
			openText1.setText(String.valueOf(day.getOpen()));
			closeText1.setText(String.valueOf(day.getClose()));
			highText1.setText(String.valueOf(day.getHigh()));
			lowText1.setText(String.valueOf(day.getLow()));
			volumeText1.setText(String.valueOf(day.getVolume()));
		}
	}
	// Event Listener on DatePicker[#changeStockPicker1].onAction
	@FXML
	public void createNewStock2(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#stockRangePicker1].onAction
	@FXML
	public void addToList2(ActionEvent event) {
		// TODO Autogenerated
	}
    @FXML
    void showMetaData(ActionEvent event) {
    	msftMeta.showAndWait();
    }

    @FXML
    void showMetaData1(ActionEvent event) {
    	adxMeta.showAndWait();
    }
}
