package demo;

import alerts.ClosedAlert;
import factories.DataFactory;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.DatePicker;
import javafx.scene.control.ListView;
import javafx.scene.input.InputMethodEvent;
import javafx.scene.text.Text;
import models.StockData;
import models.StockDay;

public class StockViewController {
	StockData msft = DataFactory.generateData("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=8Y8VNRTWK1PBQ5AU&dataype=json");
	StockData adx = DataFactory.generateData("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=ADX&apikey=8Y8VNRTWK1PBQ5AU&dataype=json");
	@FXML
	private DatePicker stockDayPicker;
	@FXML
	private DatePicker changeStockPicker;
	@FXML
	private DatePicker stockRangePicker;
	@FXML
	private ListView stockRangeList;
	@FXML
	private Text closeText;
	@FXML
	private Text openText;
	@FXML
	private Text highText;
	@FXML
	private Text lowText;
	@FXML
	private Text volumeText;
	@FXML
	private Text highestText;
	@FXML
	private Text avgText;
	@FXML
	private Text lowestText;
	@FXML
	private Text dateHighestText;
	@FXML
	private Text dateLowestText;
	@FXML
	private DatePicker stockDayPicker1;
	@FXML
	private DatePicker changeStockPicker1;
	@FXML
	private DatePicker stockRangePicker1;
	@FXML
	private ListView stockRangeList1;
	@FXML
	private Text closeText1;
	@FXML
	private Text openText1;
	@FXML
	private Text highText1;
	@FXML
	private Text lowText1;
	@FXML
	private Text volumeText1;
	@FXML
	private Text highestText1;
	@FXML
	private Text avgText1;
	@FXML
	private Text lowestText1;
	@FXML
	private Text dateHighestText1;
	@FXML
	private Text dateLowestText1;
	private ClosedAlert alert = new ClosedAlert();

	// Event Listener on DatePicker[#stockDayPicker].onAction
	@FXML
	public void findStock1(ActionEvent event) {
		StockDay day = msft.getStocks().get(stockDayPicker.getValue().toString());
		if(day == null) {
			alert.showAndWait();
		} else {
			openText.setText(String.valueOf(day.getOpen()));
			closeText.setText(String.valueOf(day.getClose()));
			highText.setText(String.valueOf(day.getHigh()));
			lowText.setText(String.valueOf(day.getLow()));
			volumeText.setText(String.valueOf(day.getVolume()));
		}
	}
	@FXML
	public void createNewStock1(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#stockRangePicker].onInputMethodTextChanged
	@FXML
	public void addToList1(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#stockDayPicker1].onInputMethodTextChanged
	@FXML
	public void findStock2(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#changeStockPicker1].onInputMethodTextChanged
	@FXML
	public void createNewStock2(InputMethodEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#stockRangePicker1].onInputMethodTextChanged
	@FXML
	public void addToList2(InputMethodEvent event) {
		// TODO Autogenerated
	}
}
